Sentence = input("Create a MADLIB!")
Name = input("Type a name: \n")
Place = input("Type a place: \n")
Verb = input("Type a verb: \n")
Noun = input("Type a noun: \n")
str(Sentence, Name)
str(Sentence, " went to ")
str(Sentence, Place)
str(Sentence, "where they ")
str(Sentence, Verb)
str(Sentence, "and bought a ")
str(Sentence, Noun)
str(Sentence, ".")