sentence = input("Create a MADLIB!")
name = input("Type a name: \n")
place = input("Type a place: \n")
verb = input("Type a verb: \n")
noun = input("Type a noun: \n")
print(sentence, name, "went to", place, "where they", verb, "and bought a", noun,".")