income = input("Hello and welcome to your financial calculator! What is your monthly income?: \n")
rent, prent, utilities, putilities = input("What is your monthly rent?: \n")
groceries, pgroceries, transportation, ptransportation = input("What is your monthly utilities?: \n")
expenses, pexpenses, savings,psavings= input("What is your monthly groceries?: \n")
input("What is your monthly transportation costs?: \n")
print(f"Your monthly income is ${"income":.2f}\n")
print(f"Your monthly expenses are ${"expenses":.2f}\n")
print(f"Your monthly savings is ${"savings":.2f}\n")
print(f"Your monthly spending money is ${"spending":.2f}\n")
print(f"Your rent is {int("prent")}% of your monthly income\n")
print(f"Your utilities are {int("putilities")}% of your monthly income \n")
print(f"Your groceries are {int("pgrocieries")}% of your monthly income \n")
print(f"Your transportation is {int("ptransportation")}% of your monthly income \n")
print(f"Your savings are {int("psavings")}% of your monthly income \n")
print(f"Your expenses are {int("pexpenses")}% of your monthly income \n")